spring:
    application:
        name: url-shortener-shortening-service
    config:
        import: "consul:"

server:
    port: ${PORT}

spring.cloud.consul:
    host: ${CONSUL_HOST}
    port: ${CONSUL_PORT}
    config:
        format: yaml
    discovery:
        tags: ${SPRING_CLOUD_CONSUL_DISCOVERY_TAGS:}
