spring:
    application:
        name: url-shortener-shortening-service
    config:
        import: "consul:"

server:
    port: 1337

spring.cloud.consul:
    host: ${CONSUL_HOST}
    port: ${CONSUL_PORT}
    config:
        format: yaml
    discovery:
        tags:
            - traefik.enable=true
            - traefik.http.routers.shortener.rule=Host(`url-shortener.dipanshushukla.com`) && (Path(`/`) || PathPrefix(`/`))
            - traefik.http.services.shortener.loadbalancer.server.port=1337
